<?php

use Illuminate\Database\Seeder;

class diadiem extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         DB::table('diadiem')->insert([
    		'idTP' => '1',
    		'idKhuVuc' => '1',
    		'image' => 'im4.jpg',
    		'ten' => 'Quán ăn gia đình 123',
    		'giaMin' => '10000',
    		'giaMax' => '100000',
    		'diaChi' => 'unknown',
    		'moTa' => 'updating',
    		'trangWeb' => 'google.com',
    		'soDienThoai' => '01234543',
    		'gioBatDau' => '7',
    		'phutBatDau' => '30',
    		'gioKetThuc' => '19',
    		'phutKetThuc' => '0',
    		]);
         DB::table('diadiem')->insert([
            'idTP' => '2',
            'idKhuVuc' => '2',
            'image' => 'im3.jpg',
            'ten' => 'Cafee gì đó ',
            'giaMin' => '10000',
            'giaMax' => '100000',
            'diaChi' => 'unknown',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '7',
            'phutBatDau' => '30',
            'gioKetThuc' => '19',
            'phutKetThuc' => '0',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '3',
            'idKhuVuc' => '3',
            'image' => 'im1.jpg',
            'ten' => 'Cơm sườn bao mắc',
            'giaMin' => '1000',
            'giaMax' => '1000000',
            'diaChi' => 'unknown',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '7',
            'phutBatDau' => '30',
            'gioKetThuc' => '19',
            'phutKetThuc' => '0',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '1',
            'idKhuVuc' => '5',
            'image' => 'im5.jpg',
            'ten' => 'Quán Cô Út - Bò Né',
            'giaMin' => '20000',
            'giaMax' => '40000',
            'diaChi' => '008 Chung Cư Phan Văn Trị, Lê Hồng Phong,  Quận 5, TP. HCM',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '11',
            'phutBatDau' => '30',
            'gioKetThuc' => '22',
            'phutKetThuc' => '30',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '1',
            'idKhuVuc' => '3',
            'image' => 'im6.jpg',
            'ten' => 'Kichi Kichi Lẩu Băng Chuyền ',
            'giaMin' => '149000',
            'giaMax' => '308000',
            'diaChi' => '84 Cao Thắng, P. 4,  Quận 3, TP. HCM',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '11',
            'phutBatDau' => '30',
            'gioKetThuc' => '22',
            'phutKetThuc' => '30',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '1',
            'idKhuVuc' => '1',
            'image' => 'im7.jpg',
            'ten' => 'Amasvin Bubble Tea',
            'giaMin' => '29000',
            'giaMax' => '60000',
            'diaChi' => '85 Hồ Tùng Mậu, P. Bến Nghé,  Quận 1, TP. HCM',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '9',
            'phutBatDau' => '30',
            'gioKetThuc' => '20',
            'phutKetThuc' => '30',
            ]);
          DB::table('diadiem')->insert([
            'idTP' => '1',
            'idKhuVuc' => '1',
            'image' => 'im4.jpg',
            'ten' => 'Quán ăn gia đình 123',
            'giaMin' => '10000',
            'giaMax' => '100000',
            'diaChi' => 'unknown',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '7',
            'phutBatDau' => '30',
            'gioKetThuc' => '19',
            'phutKetThuc' => '0',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '2',
            'idKhuVuc' => '2',
            'image' => 'im3.jpg',
            'ten' => 'Cafee gì đó ',
            'giaMin' => '10000',
            'giaMax' => '100000',
            'diaChi' => 'unknown',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '7',
            'phutBatDau' => '30',
            'gioKetThuc' => '19',
            'phutKetThuc' => '0',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '3',
            'idKhuVuc' => '3',
            'image' => 'im1.jpg',
            'ten' => 'Cơm sườn bao mắc',
            'giaMin' => '1000',
            'giaMax' => '1000000',
            'diaChi' => 'unknown',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '7',
            'phutBatDau' => '30',
            'gioKetThuc' => '19',
            'phutKetThuc' => '0',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '1',
            'idKhuVuc' => '5',
            'image' => 'im5.jpg',
            'ten' => 'Quán Cô Út - Bò Né',
            'giaMin' => '20000',
            'giaMax' => '40000',
            'diaChi' => '008 Chung Cư Phan Văn Trị, Lê Hồng Phong,  Quận 5, TP. HCM',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '11',
            'phutBatDau' => '30',
            'gioKetThuc' => '22',
            'phutKetThuc' => '30',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '1',
            'idKhuVuc' => '3',
            'image' => 'im6.jpg',
            'ten' => 'Kichi Kichi Lẩu Băng Chuyền ',
            'giaMin' => '149000',
            'giaMax' => '308000',
            'diaChi' => '84 Cao Thắng, P. 4,  Quận 3, TP. HCM',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '11',
            'phutBatDau' => '30',
            'gioKetThuc' => '22',
            'phutKetThuc' => '30',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '1',
            'idKhuVuc' => '1',
            'image' => 'im7.jpg',
            'ten' => 'Amasvin Bubble Tea',
            'giaMin' => '29000',
            'giaMax' => '60000',
            'diaChi' => '85 Hồ Tùng Mậu, P. Bến Nghé,  Quận 1, TP. HCM',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '9',
            'phutBatDau' => '30',
            'gioKetThuc' => '20',
            'phutKetThuc' => '30',
            ]);
          DB::table('diadiem')->insert([
            'idTP' => '1',
            'idKhuVuc' => '1',
            'image' => 'im4.jpg',
            'ten' => 'Quán ăn gia đình 123',
            'giaMin' => '10000',
            'giaMax' => '100000',
            'diaChi' => 'unknown',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '7',
            'phutBatDau' => '30',
            'gioKetThuc' => '19',
            'phutKetThuc' => '0',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '2',
            'idKhuVuc' => '2',
            'image' => 'im3.jpg',
            'ten' => 'Cafee gì đó ',
            'giaMin' => '10000',
            'giaMax' => '100000',
            'diaChi' => 'unknown',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '7',
            'phutBatDau' => '30',
            'gioKetThuc' => '19',
            'phutKetThuc' => '0',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '3',
            'idKhuVuc' => '3',
            'image' => 'im1.jpg',
            'ten' => 'Cơm sườn bao mắc',
            'giaMin' => '1000',
            'giaMax' => '1000000',
            'diaChi' => 'unknown',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '7',
            'phutBatDau' => '30',
            'gioKetThuc' => '19',
            'phutKetThuc' => '0',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '1',
            'idKhuVuc' => '5',
            'image' => 'im5.jpg',
            'ten' => 'Quán Cô Út - Bò Né',
            'giaMin' => '20000',
            'giaMax' => '40000',
            'diaChi' => '008 Chung Cư Phan Văn Trị, Lê Hồng Phong,  Quận 5, TP. HCM',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '11',
            'phutBatDau' => '30',
            'gioKetThuc' => '22',
            'phutKetThuc' => '30',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '1',
            'idKhuVuc' => '3',
            'image' => 'im6.jpg',
            'ten' => 'Kichi Kichi Lẩu Băng Chuyền ',
            'giaMin' => '149000',
            'giaMax' => '308000',
            'diaChi' => '84 Cao Thắng, P. 4,  Quận 3, TP. HCM',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '11',
            'phutBatDau' => '30',
            'gioKetThuc' => '22',
            'phutKetThuc' => '30',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '1',
            'idKhuVuc' => '1',
            'image' => 'im7.jpg',
            'ten' => 'Amasvin Bubble Tea',
            'giaMin' => '29000',
            'giaMax' => '60000',
            'diaChi' => '85 Hồ Tùng Mậu, P. Bến Nghé,  Quận 1, TP. HCM',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '9',
            'phutBatDau' => '30',
            'gioKetThuc' => '20',
            'phutKetThuc' => '30',
            ]);
          DB::table('diadiem')->insert([
            'idTP' => '1',
            'idKhuVuc' => '1',
            'image' => 'im4.jpg',
            'ten' => 'Quán ăn gia đình 123',
            'giaMin' => '10000',
            'giaMax' => '100000',
            'diaChi' => 'unknown',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '7',
            'phutBatDau' => '30',
            'gioKetThuc' => '19',
            'phutKetThuc' => '0',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '2',
            'idKhuVuc' => '2',
            'image' => 'im3.jpg',
            'ten' => 'Cafee gì đó ',
            'giaMin' => '10000',
            'giaMax' => '100000',
            'diaChi' => 'unknown',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '7',
            'phutBatDau' => '30',
            'gioKetThuc' => '19',
            'phutKetThuc' => '0',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '3',
            'idKhuVuc' => '3',
            'image' => 'im1.jpg',
            'ten' => 'Cơm sườn bao mắc',
            'giaMin' => '1000',
            'giaMax' => '1000000',
            'diaChi' => 'unknown',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '7',
            'phutBatDau' => '30',
            'gioKetThuc' => '19',
            'phutKetThuc' => '0',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '1',
            'idKhuVuc' => '5',
            'image' => 'im5.jpg',
            'ten' => 'Quán Cô Út - Bò Né',
            'giaMin' => '20000',
            'giaMax' => '40000',
            'diaChi' => '008 Chung Cư Phan Văn Trị, Lê Hồng Phong,  Quận 5, TP. HCM',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '11',
            'phutBatDau' => '30',
            'gioKetThuc' => '22',
            'phutKetThuc' => '30',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '1',
            'idKhuVuc' => '3',
            'image' => 'im6.jpg',
            'ten' => 'Kichi Kichi Lẩu Băng Chuyền ',
            'giaMin' => '149000',
            'giaMax' => '308000',
            'diaChi' => '84 Cao Thắng, P. 4,  Quận 3, TP. HCM',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '11',
            'phutBatDau' => '30',
            'gioKetThuc' => '22',
            'phutKetThuc' => '30',
            ]);
         DB::table('diadiem')->insert([
            'idTP' => '1',
            'idKhuVuc' => '1',
            'image' => 'im7.jpg',
            'ten' => 'Amasvin Bubble Tea',
            'giaMin' => '29000',
            'giaMax' => '60000',
            'diaChi' => '85 Hồ Tùng Mậu, P. Bến Nghé,  Quận 1, TP. HCM',
            'moTa' => 'updating',
            'trangWeb' => 'google.com',
            'soDienThoai' => '01234543',
            'gioBatDau' => '9',
            'phutBatDau' => '30',
            'gioKetThuc' => '20',
            'phutKetThuc' => '30',
            ]);
         
    }
}
